package org.gbif.material.model;

public class Common {
  public enum CommonTargetType {
    ENTITY,
    MATERIAL_ENTITY,
    MATERIAL_GROUP,
    ORGANISM,
    DIGITAL_ENTITY,
    GENETIC_SEQUENCE,
    EVENT,
    OCCURRENCE,
    LOCATION,
    GEOREFERENCE,
    GEOLOGICAL_CONTEXT,
    PROTOCOL,
    AGENT,
    COLLECTION,
    ENTITY_RELATIONSHIP,
    IDENTIFICATION,
    TAXON,
    REFERENCE,
    AGENT_GROUP,
    ASSERTION,
    CHRONOMETRIC_AGE
  }
}
